/**
 * The public client boundary.
 *
 * Feature code imports from `src/core/client` and from nowhere below it. If a
 * component needs something that is not exported here, the answer is a new
 * coarse client operation — not a reach into `src/core/runtime`.
 */

export type {
  ArchiveSurface,
  IdentitySurface,
  LifeArchiveClient,
  MediaSurface,
  OperationSurface,
  PeopleSurface,
  RecordSurface,
  RuntimeSurface,
  StructuredSurface,
  TimeSurface,
  TimelineSurface,
  TrackSurface,
} from './LifeArchiveClient'

export {
  KNOWN_FAILURE_CODES,
  assertNever,
  clientFailure,
  failed,
  failureKey,
  hasUnknownDurableOutcome,
  isKnownFailureCode,
  isOk,
  ok,
} from './errors'

export type {
  CleanupState,
  ClientFailure,
  ClientResult,
  FailureArea,
  FailureCause,
  FailureCode,
  FailurePhase,
  FailureSubject,
  KnownFailureCode,
} from './errors'

export {
  CLIENT_SURFACE,
  EXCLUDED_SURFACE_AREAS,
  describeClientSurface,
} from './capabilities'

export type {
  ClientSurfaceArea,
  ClientSurfaceMethod,
  ExcludedSurfaceArea,
} from './capabilities'

export {
  civilDate,
  coreTimeWindow,
  coreTrackHistoryCursor,
  isCivilDate,
  isRevision,
  isStableId,
  operationId,
  revision,
  stableId,
} from './types'

export type {
  ArchiveChange,
  ArchiveCloseResult,
  ArchiveEraseRequest,
  ArchiveEraseResult,
  ArchiveExportRequest,
  ArchiveExportResult,
  ArchiveHealthFacts,
  ArchiveIdentity,
  ArchiveIdentitySaveResult,
  ArchiveIdentityState,
  ArchiveImportInspectRequest,
  ArchiveImportInspection,
  ArchiveImportInspectionContext,
  ArchiveImportInspectionCounts,
  ArchiveImportInspectionIssue,
  ArchiveImportIdentityOutcome,
  ArchiveImportIssue,
  ArchiveImportRequest,
  ArchiveImportResolutionSelection,
  ArchiveImportResult,
  ArchiveImportSource,
  ArchiveOverview,
  ArchivePackage,
  ArchiveSession,
  ArchiveSubject,
  ArchiveVerification,
  ArchiveVerificationIssue,
  ArchiveVerifyRequest,
  BoundaryMarker,
  Brand,
  CalendarContext,
  CalendarContextRequest,
  CalendarDay,
  CancellationRequestResult,
  CivilDate,
  ClientMode,
  ContentSource,
  CountedEntryKind,
  DurableOutcome,
  Instant,
  InvalidationToken,
  LifeStatus,
  MarkerConfiguration,
  MediaContent,
  MediaContentRequest,
  MediaDeleteRequest,
  MediaDeleteResult,
  MediaImportRequest,
  MediaImportResult,
  MediaItem,
  MediaKind,
  MediaListRequest,
  MediaListing,
  OpenArchive,
  OperationId,
  OrdinaryDeleteRequest,
  OrdinaryDeleteResult,
  OrdinaryConflictState,
  OrdinaryEntry,
  OrdinaryEntryState,
  OrdinarySaveRequest,
  OrdinarySaveResult,
  OrdinaryTarget,
  EntryPeopleSnapshot,
  EntryPersonLink,
  EntrySectionId,
  LinkedPersonSnapshot,
  Person,
  PersonContactDay,
  PersonContactHistoryPage,
  PersonContactHistoryRange,
  PersonContactHistoryRequest,
  PersonContactPeriodSummary,
  PersonContactSummary,
  PersonContactSummaryRequest,
  PersonContactSummaryResult,
  PersonCreateRequest,
  PersonDate,
  PersonDatePrecision,
  PersonDeleteRequest,
  PersonDeleteResult,
  PersonInteractionLevel,
  PersonLifeStatus,
  PersonLinkDraft,
  PersonListCursor,
  PersonListPage,
  PersonListRequest,
  PersonLoadResult,
  PersonLogContactRequest,
  PersonMemoriesPage,
  PersonMemoriesRequest,
  PersonMemorySummary,
  PersonMergeAboutSource,
  PersonMergePhotoSource,
  PersonMergeProfileSource,
  PersonMergeRequest,
  PersonMergeResult,
  PersonMutationResult,
  PersonOtherName,
  PersonOtherNameKindId,
  PersonPhotoImportRequest,
  PersonPhotoMutationResult,
  PersonPhotoRemoveRequest,
  PersonProfile,
  PersonProfilePhoto,
  PersonReference,
  PersonReferenceKindId,
  PersonSaveRequest,
  PersonSnapshot,
  RecordPeopleLoadRequest,
  RecordPeopleLoadResult,
  RecordPeopleMutation,
  RecordPeopleMutationRequest,
  RecordPeopleMutationResult,
  RecordPeopleTarget,
  PersistenceGrant,
  PrivacyLevel,
  Revision,
  RevisionConflict,
  RuntimeFacts,
  RuntimeIncompatibleReason,
  RuntimeStatus,
  RuntimeUnavailableReason,
  SemanticId,
  StableId,
  StorageDurability,
  StorageEstimate,
  StorageFacts,
  StructuredConvertRequest,
  StructuredConflictState,
  StructuredCreateRequest,
  StructuredDeleteRequest,
  StructuredDeleteResult,
  StructuredDraft,
  StructuredKind,
  StructuredListPage,
  StructuredListRequest,
  StructuredLoadRequest,
  StructuredMutationResult,
  StructuredObject,
  StructuredObjectState,
  StructuredPlacement,
  StructuredSaveRequest,
  StructuredSummary,
  StructuredTags,
  TimeScale,
  TimeWindow,
  TimeWindowFields,
  TimeWindowRequest,
  TimelineEntryReference,
  TimelineFocusRequest,
  TimelineFocusResult,
  TimelineFocusedEntry,
  TimelineIndexRequest,
  TimelinePage,
  TimelineRow,
  TimelineStructuredDetailRequest,
  TimelineStructuredDetailResult,
  TimelineStructuredListRequest,
  TimelineStructuredListResult,
  Track,
  TrackConflictState,
  TrackCreateRequest,
  TrackDeleteRequest,
  TrackDetachRequest,
  TrackDraft,
  TrackHistoryCursor,
  TrackHistoryPage,
  TrackHistoryRequest,
  TrackListPage,
  TrackListRequest,
  TrackMember,
  TrackMemberCreateRequest,
  TrackMembershipRequest,
  TrackMutationResult,
  TrackSaveRequest,
  TrackState,
  TrackSummary,
  TrackWithFirstMember,
  TrackWithFirstMemberRequest,
  Unsubscribe,
  WeekRules,
  WindowStep,
  WindowStepRequest,
} from './types'
