// Generated during a coordinated LifeArchive release from the Rust-owned semantic icon catalogue.
// Public value metadata only. Do not edit by hand.

export const SEMANTIC_ICON_CATALOG_VERSION = 1 as const
export const EVENT_DEFAULT_ICON_ID = 'life-event'
export const SPAN_DEFAULT_ICON_ID = 'span'

export const SEMANTIC_ICON_CATEGORIES = [
  {
    id: 'life-change',
    icons: [
      'life-event',
      'new-child',
      'birthday',
      'growing-up',
      'new-beginning',
      'transition',
      'turning-point',
      'farewell',
      'loss',
      'legacy',
      'identity',
      'faith',
    ],
  },
  {
    id: 'relationships-people',
    icons: [
      'love',
      'partnership',
      'commitment',
      'family',
      'friendship',
      'individual',
      'parenthood',
      'community',
      'visitor',
      'support',
      'separation',
      'broken-heart',
    ],
  },
  {
    id: 'home-possessions',
    icons: [
      'home',
      'keys',
      'moving-home',
      'home-purchase',
      'renovation',
      'repair',
      'stay',
      'belongings',
      'purchase',
      'valuable',
      'household',
      'loss-damage',
    ],
  },
  {
    id: 'work-money',
    icons: [
      'job',
      'workplace',
      'new-job',
      'career-change',
      'promotion',
      'business',
      'launch',
      'career-progress',
      'meeting',
      'remote-work',
      'money',
      'dollarsign',
      'contract',
      'retirement',
    ],
  },
  {
    id: 'learning-growth',
    icons: [
      'graduation',
      'school',
      'book',
      'study',
      'course',
      'certificate',
      'research',
      'practice',
      'language',
      'exam',
    ],
  },
  {
    id: 'travel-places',
    icons: [
      'flight',
      'car',
      'train',
      'bus',
      'bicycle',
      'motorcycle',
      'boat',
      'sailing',
      'walking',
      'luggage',
      'map',
      'place',
      'world',
      'camping',
    ],
  },
  {
    id: 'health-wellbeing',
    icons: [
      'health',
      'medical-care',
      'illness',
      'diagnosis',
      'medication',
      'injury',
      'treatment',
      'recovery',
      'exercise',
      'mental-health',
      'sleep',
      'accessibility',
      'habit',
    ],
  },
  {
    id: 'creativity-projects',
    icons: [
      'art',
      'photography',
      'music',
      'writing',
      'film',
      'performance',
      'design',
      'craft',
      'coding',
      'cooking',
      'reading',
      'project',
      'rocket-launch',
      'idea',
      'finished-work',
    ],
  },
  {
    id: 'achievement-sport',
    icons: [
      'achievement',
      'medal',
      'recognition',
      'goal',
      'competition',
      'record',
      'win',
      'completion',
      'team-sport',
      'ball-sport',
      'swimming',
      'winter-sport',
      'strength',
      'personal-best',
    ],
  },
  {
    id: 'hobbies-digital',
    icons: [
      'gaming',
      'computer',
      'phone',
      'technology',
      'app',
      'internet',
      'television',
      'audio',
      'puzzle',
      'collection',
      'making',
      'intense-focus',
      'social',
      'machinery',
    ],
  },
  {
    id: 'nature-animals',
    icons: [
      'nature',
      'outdoors',
      'water',
      'mountain',
      'forest',
      'flowers',
      'sun',
      'fire',
      'pet',
      'wildlife',
      'weather',
      'ocean',
    ],
  },
  {
    id: 'occasions-general',
    icons: [
      'span',
      'celebration',
      'holiday',
      'gift',
      'food-drink',
      'event',
      'announcement',
      'time',
      'worth-noting',
      'special',
      'night',
      'emergency',
      'legal',
      'safety',
      'other',
    ],
  },
] as const

export type BuiltInSemanticIconId =
  (typeof SEMANTIC_ICON_CATEGORIES)[number]['icons'][number]

export const ORDERED_SEMANTIC_ICON_IDS = SEMANTIC_ICON_CATEGORIES.flatMap(
  ({ icons }) => icons,
) as readonly BuiltInSemanticIconId[]
