import type { SemanticId, StructuredTags } from '../../../core/client'

export const SEMANTIC_ICON_CATALOG_VERSION = 1
export const EVENT_DEFAULT_ICON_ID = 'life-event'
export const SPAN_DEFAULT_ICON_ID = 'span'

export const SEMANTIC_ICON_CATEGORIES = [
  {
    id: 'life-change',
    icons: [
      'life-event',
      'new-child',
      'birthday',
      'growing-up',
      'new-beginning',
      'transition',
      'turning-point',
      'farewell',
      'loss',
      'legacy',
      'identity',
      'faith',
    ],
  },
  {
    id: 'relationships-people',
    icons: [
      'love',
      'partnership',
      'commitment',
      'family',
      'friendship',
      'individual',
      'parenthood',
      'community',
      'visitor',
      'support',
      'separation',
      'broken-heart',
    ],
  },
  {
    id: 'home-possessions',
    icons: [
      'home',
      'keys',
      'moving-home',
      'home-purchase',
      'renovation',
      'repair',
      'stay',
      'belongings',
      'purchase',
      'valuable',
      'household',
      'loss-damage',
    ],
  },
  {
    id: 'work-money',
    icons: [
      'job',
      'workplace',
      'new-job',
      'career-change',
      'promotion',
      'business',
      'launch',
      'career-progress',
      'meeting',
      'remote-work',
      'money',
      'dollarsign',
      'contract',
      'retirement',
    ],
  },
  {
    id: 'learning-growth',
    icons: [
      'graduation',
      'school',
      'book',
      'study',
      'course',
      'certificate',
      'research',
      'practice',
      'language',
      'exam',
    ],
  },
  {
    id: 'travel-places',
    icons: [
      'flight',
      'car',
      'train',
      'bus',
      'bicycle',
      'motorcycle',
      'boat',
      'sailing',
      'walking',
      'luggage',
      'map',
      'place',
      'world',
      'camping',
    ],
  },
  {
    id: 'health-wellbeing',
    icons: [
      'health',
      'medical-care',
      'illness',
      'diagnosis',
      'medication',
      'injury',
      'treatment',
      'recovery',
      'exercise',
      'mental-health',
      'sleep',
      'accessibility',
      'habit',
    ],
  },
  {
    id: 'creativity-projects',
    icons: [
      'art',
      'photography',
      'music',
      'writing',
      'film',
      'performance',
      'design',
      'craft',
      'coding',
      'cooking',
      'reading',
      'project',
      'rocket-launch',
      'idea',
      'finished-work',
    ],
  },
  {
    id: 'achievement-sport',
    icons: [
      'achievement',
      'medal',
      'recognition',
      'goal',
      'competition',
      'record',
      'win',
      'completion',
      'team-sport',
      'ball-sport',
      'swimming',
      'winter-sport',
      'strength',
      'personal-best',
    ],
  },
  {
    id: 'hobbies-digital',
    icons: [
      'gaming',
      'computer',
      'phone',
      'technology',
      'app',
      'internet',
      'television',
      'audio',
      'puzzle',
      'collection',
      'making',
      'intense-focus',
      'social',
      'machinery',
    ],
  },
  {
    id: 'nature-animals',
    icons: [
      'nature',
      'outdoors',
      'water',
      'mountain',
      'forest',
      'flowers',
      'sun',
      'fire',
      'pet',
      'wildlife',
      'weather',
      'ocean',
    ],
  },
  {
    id: 'occasions-general',
    icons: [
      'span',
      'celebration',
      'holiday',
      'gift',
      'food-drink',
      'event',
      'announcement',
      'time',
      'worth-noting',
      'special',
      'night',
      'emergency',
      'legal',
      'safety',
      'other',
    ],
  },
] as const

export type BuiltInSemanticIconId =
  (typeof SEMANTIC_ICON_CATEGORIES)[number]['icons'][number]

export const ORDERED_SEMANTIC_ICON_IDS = SEMANTIC_ICON_CATEGORIES.flatMap(
  ({ icons }) => icons,
) as readonly BuiltInSemanticIconId[]

export const MATERIAL_ICON_BY_SEMANTIC_ID = {
  'life-event': 'flag',
  'new-child': 'stroller',
  birthday: 'cake',
  'growing-up': 'boy',
  'new-beginning': 'wb_twilight',
  transition: 'autorenew',
  'turning-point': 'turn_right',
  farewell: 'wb_twilight_2',
  loss: 'candle',
  legacy: 'history_edu',
  identity: 'account_circle',
  faith: 'folded_hands',
  love: 'favorite',
  partnership: 'partner_heart',
  commitment: 'link_2',
  family: 'family_restroom',
  friendship: 'group',
  individual: 'person',
  parenthood: 'escalator_warning',
  community: 'diversity_3',
  visitor: 'person_add',
  support: 'volunteer_activism',
  separation: 'group_off',
  'broken-heart': 'heart_broken',
  home: 'home',
  keys: 'key',
  'moving-home': 'home_pin',
  'home-purchase': 'add_home',
  renovation: 'hardware',
  repair: 'handyman',
  stay: 'bed',
  belongings: 'package_2',
  purchase: 'shopping_bag',
  valuable: 'diamond',
  household: 'laundry',
  'loss-damage': 'lock_open_right',
  job: 'business_center',
  workplace: 'domain',
  'new-job': 'badge',
  'career-change': 'swap_horiz',
  promotion: 'upgrade',
  business: 'store',
  launch: 'near_me',
  'career-progress': 'trending_up',
  meeting: 'communication',
  'remote-work': 'laptop_mac',
  money: 'payments',
  dollarsign: 'attach_money',
  contract: 'description',
  retirement: 'beach_access',
  graduation: 'school',
  school: 'account_balance',
  book: 'book_2',
  study: 'edit',
  course: 'collections_bookmark',
  certificate: 'verified',
  research: 'search',
  practice: 'repeat',
  language: 'dictionary',
  exam: 'assignment',
  flight: 'flight',
  car: 'directions_car',
  train: 'train',
  bus: 'directions_bus',
  bicycle: 'directions_bike',
  motorcycle: 'two_wheeler',
  boat: 'directions_boat',
  sailing: 'sailing',
  walking: 'directions_walk',
  luggage: 'luggage',
  map: 'map',
  place: 'location_on',
  world: 'public',
  camping: 'camping',
  health: 'diagnosis',
  'medical-care': 'medical_services',
  illness: 'sick',
  diagnosis: 'stethoscope',
  medication: 'pill',
  injury: 'healing',
  treatment: 'syringe',
  recovery: 'monitor_heart',
  exercise: 'directions_run',
  'mental-health': 'self_improvement',
  sleep: 'bedtime',
  accessibility: 'accessible',
  habit: 'cycle',
  art: 'palette',
  photography: 'photo_camera',
  music: 'music_note',
  writing: 'edit_note',
  film: 'theaters',
  performance: 'theater_comedy',
  design: 'design_services',
  craft: 'content_cut',
  coding: 'code_blocks',
  cooking: 'restaurant',
  reading: 'newsstand',
  project: 'folder_open',
  'rocket-launch': 'rocket_launch',
  idea: 'emoji_objects',
  'finished-work': 'fact_check',
  achievement: 'trophy',
  medal: 'license',
  recognition: 'star',
  goal: 'target',
  competition: 'sports_score',
  record: 'timer',
  win: 'workspace_premium',
  completion: 'check_circle',
  'team-sport': 'sports_soccer',
  'ball-sport': 'sports_basketball',
  swimming: 'pool',
  'winter-sport': 'downhill_skiing',
  strength: 'fitness_center',
  'personal-best': 'bar_chart_4_bars',
  gaming: 'sports_esports',
  computer: 'desktop_windows',
  phone: 'phone_iphone',
  technology: 'memory',
  app: 'apps',
  internet: 'language',
  television: 'live_tv',
  audio: 'headphones',
  puzzle: 'extension',
  collection: 'grid_view',
  making: 'tools_wrench',
  'intense-focus': 'center_focus_strong',
  social: 'forum',
  machinery: 'manufacturing',
  nature: 'nest_eco_leaf',
  outdoors: 'hiking',
  water: 'water_drop',
  mountain: 'landscape',
  forest: 'nature',
  flowers: 'local_florist',
  sun: 'light_mode',
  fire: 'local_fire_department',
  pet: 'pets',
  wildlife: 'raven',
  weather: 'partly_cloudy_day',
  ocean: 'waves',
  span: 'calendar_month',
  celebration: 'celebration',
  holiday: 'attractions',
  gift: 'featured_seasonal_and_gifts',
  'food-drink': 'local_cafe',
  event: 'confirmation_number',
  announcement: 'campaign',
  time: 'schedule',
  'worth-noting': 'bookmark',
  special: 'auto_awesome',
  night: 'moon_stars',
  emergency: 'warning',
  legal: 'signature',
  safety: 'shield',
  other: 'pending',
} as const satisfies Record<BuiltInSemanticIconId, string>

export function materialIconFor(id: SemanticId): string | null {
  return Object.hasOwn(MATERIAL_ICON_BY_SEMANTIC_ID, id)
    ? MATERIAL_ICON_BY_SEMANTIC_ID[
        id as keyof typeof MATERIAL_ICON_BY_SEMANTIC_ID
      ]
    : null
}

/** Non-semantic Material glyphs used by the picker controls and fallback. */
export const MATERIAL_UI_GLYPHS = {
  all: 'grid_view',
  unknown: 'question_mark',
  selected: 'check_box',
  unselected: 'check_box_outline_blank',
  main: 'star',
  notMain: 'star_outline',
} as const

export const PREDEFINED_TAG_IDS = [
  'personal',
  'family',
  'friends',
  'work',
  'education',
  'travel',
  'home',
  'health',
  'creative',
  'achievement',
] as const

export type PredefinedTagId = (typeof PREDEFINED_TAG_IDS)[number]
export type TagPaletteId = PredefinedTagId | 'fallback'

export function tagPaletteFor(id: SemanticId): TagPaletteId {
  return (PREDEFINED_TAG_IDS as readonly string[]).includes(id)
    ? (id as PredefinedTagId)
    : 'fallback'
}

export function displayAccentClassName(id: SemanticId | null): string {
  return id ? `record-display-accent--${tagPaletteFor(id)}` : ''
}

export function addTag(tags: StructuredTags, id: SemanticId): StructuredTags {
  if (tags.ordered.includes(id)) return tags
  const ordered = [...tags.ordered, id]
  return { ordered, display: tags.display ?? id }
}

export function removeTag(
  tags: StructuredTags,
  id: SemanticId,
): StructuredTags {
  const ordered = tags.ordered.filter((tag) => tag !== id)
  return {
    ordered,
    display: tags.display === id ? (ordered[0] ?? null) : tags.display,
  }
}

export function chooseDisplayTag(
  tags: StructuredTags,
  id: SemanticId,
): StructuredTags {
  return tags.ordered.includes(id) ? { ...tags, display: id } : tags
}
